apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: modify-pods-to-sa
subjects:
  - kind: ServiceAccount
    name: {{ include "kubectl.serviceAccountName" . }}
    namespace: default
roleRef:
  kind: Role
  name: modify-pods
  apiGroup: rbac.authorization.k8s.io