apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubectl.fullname" . }}
  labels:
    {{- include "kubectl.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.srcPort }}
      targetPort: {{ .Values.service.destPort }}
      protocol: TCP
      name: ssh
  selector:
    {{- include "kubectl.selectorLabels" . | nindent 4 }}
